# Generated by Django 5.0.1 on 2026-02-24 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('seed_rank', models.IntegerField()),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='pools.pool')),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['seed_rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_round', models.IntegerField()),
                ('pick_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='pools.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='users.user')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_pick', to='teams.team')),
            ],
            options={
                'db_table': 'draft_picks',
                'ordering': ['pick_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(check=models.Q(('seed_rank__gte', 1), ('seed_rank__lte', 16)), name='seed_rank_valid_range'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('pool', 'name')},
        ),
        migrations.AddConstraint(
            model_name='draftpick',
            constraint=models.CheckConstraint(check=models.Q(('draft_round__gte', 1), ('draft_round__lte', 5)), name='draft_round_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='draftpick',
            constraint=models.CheckConstraint(check=models.Q(('pick_order__gte', 1), ('pick_order__lte', 60)), name='pick_order_valid_range'),
        ),
        migrations.AlterUniqueTogether(
            name='draftpick',
            unique_together={('pool', 'pick_order'), ('pool', 'team')},
        ),
    ]
