# Generated by Django 5.0.1 on 2026-03-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
        ('teams', '0002_add_team_elimination_tracking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='elimination_round_valid_range',
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('elimination_round__gte', 1), ('elimination_round__lte', 6)), ('elimination_round__isnull', True), _connector='OR'), name='elimination_round_valid_range'),
        ),
    ]
