# Generated by Django 5.0.1 on 2026-02-24 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pools', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGameResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tournament_round', models.IntegerField()),
                ('result', models.CharField(choices=[('WON', 'Won'), ('LOST', 'Lost'), ('NOT_PLAYED', 'Not Played')], default='NOT_PLAYED', max_length=20)),
                ('points_awarded', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to='pools.pool')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to='teams.team')),
            ],
            options={
                'db_table': 'team_game_results',
                'ordering': ['tournament_round'],
            },
        ),
        migrations.AddConstraint(
            model_name='teamgameresult',
            constraint=models.CheckConstraint(check=models.Q(('tournament_round__gte', 1), ('tournament_round__lte', 6)), name='tournament_round_valid_range'),
        ),
        migrations.AlterUniqueTogether(
            name='teamgameresult',
            unique_together={('pool', 'team', 'tournament_round')},
        ),
    ]
