# Generated by Django 5.0.1 on 2026-02-24 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('url_slug', models.SlugField(max_length=255, unique=True)),
                ('draft_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('max_members', models.IntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_pools', to='users.user')),
            ],
            options={
                'db_table': 'pools',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoolMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_position', models.IntegerField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pools.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='users.user')),
            ],
            options={
                'db_table': 'pool_memberships',
                'ordering': ['-total_points'],
            },
        ),
        migrations.AddConstraint(
            model_name='poolmembership',
            constraint=models.CheckConstraint(check=models.Q(('draft_position__gte', 1), ('draft_position__isnull', True), _connector='OR'), name='draft_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='poolmembership',
            constraint=models.CheckConstraint(check=models.Q(('draft_position__lte', 12), ('draft_position__isnull', True), _connector='OR'), name='draft_position_max_12'),
        ),
        migrations.AlterUniqueTogether(
            name='poolmembership',
            unique_together={('pool', 'draft_position'), ('pool', 'user')},
        ),
    ]
